// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://viwfeqkuwblobybygilr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpd2ZlcWt1d2Jsb2J5YnlnaWxyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNjE0NjksImV4cCI6MjA2MzczNzQ2OX0.FCRv7YwRSoWIJ38Sa7P0G2H5IeFWTTuNHw0p1YdqV10";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);